function sideband_coefs = get_region_coefs(vm, carrier_type, m)
    % GET_REGION_COEFS Computes sideband coefficients for a given region.
    % The time domain PWM signal is considered to oscilate between
    % 1 and -1 and generated by comparing the modulating 
    % signal, vm, with a triangular carrier with amplitude 1 and frequency
    % mf times the frequency of vm.
    %
    % Warning: This function does not take into account the effect of
    % neighboring regions, which can be noticeable for large m or small mf.
    %
    % Arguments:
    %   vm (vector): A vector containing one period of the modulating signal.
    %   carrier_type (int): Specifies the type of carrier:
    %                       1 for symmetric carriers,
    %                       2 for leading-edge sawtooth carriers,
    %                       3 for trailling-edge sawtooth carriers.
    %   m (int): The region to be computed.
    %
    % Returns:
    %   sideband_coefs (vector): Vector of complex values, A_i + j B_i,
    %       where A_i and B_i are the coefficients (in cosine-sine form) of
    %       the the harmonics of region m. Only the right-hand side of the
    %       reguon is returned.
    
    if m == 0
        f = 2*vm;
    elseif carrier_type == 1
        f = (4/(m*pi))*sin(m*pi*(1 + vm)/2);
    elseif carrier_type == 2
        f = (2/(m*pi))*(sin(m*pi*vm) + 1i*cos(m*pi*vm) - (-1)^m);
    elseif carrier_type == 3
        f = (2/(m*pi))*(sin(m*pi*vm) - 1i*cos(m*pi*vm) - (-1)^m);
    else
        error(strcat('Invalid carrier_type. It must be 1 (symmetric)',...
              '2 (leading-edge), or 3 (trailling-edge).'));
    end
    ifft_raw = ifft(f);
    sideband_coefs = ifft_raw(1:round(end/2)); 
end
